// <auto-generated />
using DND_Initiative_Tracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DND_Initiative_Tracker.Migrations
{
    [DbContext(typeof(DnDDbContext))]
    partial class DnDDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "action_type", new[] { "action", "bonus_action", "reaction", "trait", "legendary_action", "lair_action", "mythical_action" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "damage_type_category", new[] { "resistant", "vulnerable", "immune", "none" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "death_status", new[] { "stable", "alive", "dying", "dead" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "size", new[] { "Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "skill_type", new[] { "skill", "tool", "instrument" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DND_Initiative_Tracker.Models.AbilityScoreType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_ability_score_types");

                    b.ToTable("ability_score_types", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.ActionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionType")
                        .HasColumnType("integer")
                        .HasColumnName("action_type");

                    b.Property<int?>("Area")
                        .HasColumnType("integer")
                        .HasColumnName("area");

                    b.Property<int?>("AttackBonus")
                        .HasColumnType("integer")
                        .HasColumnName("attack_bonus");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("Range")
                        .HasColumnType("integer")
                        .HasColumnName("range");

                    b.Property<int?>("Reach")
                        .HasColumnType("integer")
                        .HasColumnName("reach");

                    b.Property<string>("Recharge")
                        .HasColumnType("text")
                        .HasColumnName("recharge");

                    b.Property<string>("SaveDc")
                        .HasColumnType("text")
                        .HasColumnName("save_dc");

                    b.HasKey("Id")
                        .HasName("pk_actions");

                    b.HasIndex("ActionType")
                        .HasDatabaseName("idx_action_type");

                    b.ToTable("actions", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_app_user_role_id");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DriveLink")
                        .HasColumnType("text")
                        .HasColumnName("drive_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("VttLink")
                        .HasColumnType("text")
                        .HasColumnName("vtt_link");

                    b.HasKey("Id")
                        .HasName("pk_campaigns");

                    b.ToTable("campaigns", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CampaignUser", b =>
                {
                    b.Property<int>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("CampaignId", "UserId")
                        .HasName("pk_campaign_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_campaign_users_user_id");

                    b.ToTable("campaign_users", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_conditions");

                    b.ToTable("conditions", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Ac")
                        .HasColumnType("integer")
                        .HasColumnName("ac");

                    b.Property<int?>("Hp")
                        .HasColumnType("integer")
                        .HasColumnName("hp");

                    b.Property<int?>("HpDiceBonus")
                        .HasColumnType("integer")
                        .HasColumnName("hp_dice_bonus");

                    b.Property<int?>("HpDiceCount")
                        .HasColumnType("integer")
                        .HasColumnName("hp_dice_count");

                    b.Property<int?>("HpDiceSize")
                        .HasColumnType("integer")
                        .HasColumnName("hp_dice_size");

                    b.Property<int?>("InitiativeBonus")
                        .HasColumnType("integer")
                        .HasColumnName("initiative_bonus");

                    b.Property<bool?>("IsNpc")
                        .HasColumnType("boolean")
                        .HasColumnName("is_npc");

                    b.Property<int?>("LairInitiative")
                        .HasColumnType("integer")
                        .HasColumnName("lair_initiative");

                    b.Property<int?>("LegendaryActionCharges")
                        .HasColumnType("integer")
                        .HasColumnName("legendary_action_charges");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("OwnerUserId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_user_id");

                    b.Property<int?>("ProficiencyBonus")
                        .HasColumnType("integer")
                        .HasColumnName("proficiency_bonus");

                    b.Property<int?>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("pk_creatures");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("idx_user_owner_creature");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_creatures_type_id");

                    b.ToTable("creatures", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureAbilityScores", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("AbilityScoreId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_score_id");

                    b.Property<bool?>("IsSavingThrowProficient")
                        .HasColumnType("boolean")
                        .HasColumnName("is_saving_throw_proficient");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("CreatureId", "AbilityScoreId")
                        .HasName("pk_creature_ability_scores");

                    b.HasIndex("AbilityScoreId")
                        .HasDatabaseName("ix_creature_ability_scores_ability_score_id");

                    b.ToTable("creature_ability_scores", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureAction", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("ActionId")
                        .HasColumnType("integer")
                        .HasColumnName("action_id");

                    b.Property<bool?>("SpellPrepared")
                        .HasColumnType("boolean")
                        .HasColumnName("spell_prepared");

                    b.HasKey("CreatureId", "ActionId")
                        .HasName("pk_creature_actions");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("ix_creature_actions_action_id");

                    b.ToTable("creature_actions", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureCondition", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("ConditionId")
                        .HasColumnType("integer")
                        .HasColumnName("condition_id");

                    b.Property<int?>("ConditionLength")
                        .HasColumnType("integer")
                        .HasColumnName("condition_length");

                    b.HasKey("CreatureId", "ConditionId")
                        .HasName("pk_creature_conditions");

                    b.HasIndex("ConditionId")
                        .HasDatabaseName("ix_creature_conditions_condition_id");

                    b.ToTable("creature_conditions", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureDamageType", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("DamageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_id");

                    b.Property<int?>("DamageTypeCategory")
                        .HasColumnType("integer")
                        .HasColumnName("damage_type_category");

                    b.HasKey("CreatureId", "DamageTypeId")
                        .HasName("pk_creature_damage_types");

                    b.HasIndex("DamageTypeCategory")
                        .HasDatabaseName("idx_damage_type_category");

                    b.HasIndex("DamageTypeId")
                        .HasDatabaseName("ix_creature_damage_types_damage_type_id");

                    b.ToTable("creature_damage_types", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureEncounter", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("EncounterId")
                        .HasColumnType("integer")
                        .HasColumnName("encounter_id");

                    b.Property<int?>("CurrentHp")
                        .HasColumnType("integer")
                        .HasColumnName("current_hp");

                    b.Property<int?>("DeathStatus")
                        .HasColumnType("integer")
                        .HasColumnName("death_status");

                    b.Property<decimal?>("Initiative")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("initiative");

                    b.Property<int?>("TempHp")
                        .HasColumnType("integer")
                        .HasColumnName("temp_hp");

                    b.HasKey("CreatureId", "EncounterId")
                        .HasName("pk_creature_encounters");

                    b.HasIndex("DeathStatus")
                        .HasDatabaseName("idx_encounter_death_status");

                    b.HasIndex("EncounterId", "Initiative")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_initiative");

                    b.ToTable("creature_encounters", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureLanguage", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("CreatureId", "LanguageId")
                        .HasName("pk_creature_languages");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_creature_languages_language_id");

                    b.ToTable("creature_languages", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureSense", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("SenseId")
                        .HasColumnType("integer")
                        .HasColumnName("sense_id");

                    b.Property<int?>("Distance")
                        .HasColumnType("integer")
                        .HasColumnName("distance");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.HasKey("CreatureId", "SenseId")
                        .HasName("pk_creature_senses");

                    b.HasIndex("SenseId")
                        .HasDatabaseName("ix_creature_senses_sense_id");

                    b.ToTable("creature_senses", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureSkill", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer")
                        .HasColumnName("skill_id");

                    b.Property<int?>("BonusOverride")
                        .HasColumnType("integer")
                        .HasColumnName("bonus_override");

                    b.Property<bool?>("IsExpertise")
                        .HasColumnType("boolean")
                        .HasColumnName("is_expertise");

                    b.Property<bool?>("IsProficient")
                        .HasColumnType("boolean")
                        .HasColumnName("is_proficient");

                    b.HasKey("CreatureId", "SkillId")
                        .HasName("pk_creature_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_creature_skills_skill_id");

                    b.ToTable("creature_skills", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureSpeed", b =>
                {
                    b.Property<int>("CreatureId")
                        .HasColumnType("integer")
                        .HasColumnName("creature_id");

                    b.Property<int>("SpeedId")
                        .HasColumnType("integer")
                        .HasColumnName("speed_id");

                    b.Property<bool?>("IsHover")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hover");

                    b.Property<int?>("SpeedValue")
                        .HasColumnType("integer")
                        .HasColumnName("speed_value");

                    b.HasKey("CreatureId", "SpeedId")
                        .HasName("pk_creature_speeds");

                    b.HasIndex("SpeedId")
                        .HasDatabaseName("ix_creature_speeds_speed_id");

                    b.ToTable("creature_speeds", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_creature_types");

                    b.ToTable("creature_types", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.DamageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_damage_types");

                    b.ToTable("damage_types", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer")
                        .HasColumnName("campaign_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("TurnCount")
                        .HasColumnType("integer")
                        .HasColumnName("turn_count");

                    b.HasKey("Id")
                        .HasName("pk_encounters");

                    b.HasIndex("CampaignId")
                        .HasDatabaseName("ix_encounters_campaign_id");

                    b.ToTable("encounters", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Sense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_senses");

                    b.ToTable("senses", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("SkillType")
                        .HasColumnType("integer")
                        .HasColumnName("skill_type");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("SkillType")
                        .HasDatabaseName("idx_skill_type");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Speed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_speeds");

                    b.ToTable("speeds", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Concentration")
                        .HasColumnType("boolean")
                        .HasColumnName("concentration");

                    b.Property<int?>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration");

                    b.Property<string>("School")
                        .HasColumnType("text")
                        .HasColumnName("school");

                    b.HasKey("Id")
                        .HasName("pk_spells");

                    b.ToTable("spells", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.SpellAction", b =>
                {
                    b.Property<int>("SpellId")
                        .HasColumnType("integer")
                        .HasColumnName("spell_id");

                    b.Property<int>("ActionId")
                        .HasColumnType("integer")
                        .HasColumnName("action_id");

                    b.HasKey("SpellId", "ActionId")
                        .HasName("pk_spell_actions");

                    b.HasIndex("ActionId")
                        .HasDatabaseName("ix_spell_actions_action_id");

                    b.ToTable("spell_actions", (string)null);
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.AppUser", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Role", "Role")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_app_user_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CampaignUser", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Campaign", "Campaign")
                        .WithMany("CampaignUsers")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_users_campaigns_campaign_id");

                    b.HasOne("DND_Initiative_Tracker.Models.AppUser", "User")
                        .WithMany("CampaignUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_campaign_users_app_user_user_id");

                    b.Navigation("Campaign");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Creature", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.AppUser", "OwnerUser")
                        .WithMany("OwnedCreatures")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_creatures_app_user_owner_user_id");

                    b.HasOne("DND_Initiative_Tracker.Models.CreatureType", "Type")
                        .WithMany("Creatures")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_creatures_creature_types_type_id");

                    b.Navigation("OwnerUser");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureAbilityScores", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.AbilityScoreType", "AbilityScoreType")
                        .WithMany("CreatureScores")
                        .HasForeignKey("AbilityScoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_ability_scores_ability_score_types_ability_score_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("AbilityScores")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_ability_scores_creatures_creature_id");

                    b.Navigation("AbilityScoreType");

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureAction", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.ActionEntity", "Action")
                        .WithMany("CreatureActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_actions_actions_action_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("Actions")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_actions_creatures_creature_id");

                    b.Navigation("Action");

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureCondition", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Condition", "Condition")
                        .WithMany("CreatureConditions")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_conditions_conditions_condition_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("Conditions")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_conditions_creatures_creature_id");

                    b.Navigation("Condition");

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureDamageType", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("DamageTypes")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_damage_types_creatures_creature_id");

                    b.HasOne("DND_Initiative_Tracker.Models.DamageType", "DamageType")
                        .WithMany("CreatureDamageTypes")
                        .HasForeignKey("DamageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_damage_types_damage_types_damage_type_id");

                    b.Navigation("Creature");

                    b.Navigation("DamageType");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureEncounter", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("CreatureEncounters")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_encounters_creatures_creature_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Encounter", "Encounter")
                        .WithMany("CreatureEncounters")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_encounters_encounters_encounter_id");

                    b.Navigation("Creature");

                    b.Navigation("Encounter");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureLanguage", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("Languages")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_languages_creatures_creature_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Language", "Language")
                        .WithMany("CreatureLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_languages_languages_language_id");

                    b.Navigation("Creature");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureSense", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("Senses")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_senses_creatures_creature_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Sense", "Sense")
                        .WithMany("CreatureSenses")
                        .HasForeignKey("SenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_senses_senses_sense_id");

                    b.Navigation("Creature");

                    b.Navigation("Sense");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureSkill", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("Skills")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_skills_creatures_creature_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Skill", "Skill")
                        .WithMany("CreatureSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_skills_skills_skill_id");

                    b.Navigation("Creature");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureSpeed", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Creature", "Creature")
                        .WithMany("Speeds")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_speeds_creatures_creature_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Speed", "Speed")
                        .WithMany("CreatureSpeeds")
                        .HasForeignKey("SpeedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_creature_speeds_speeds_speed_id");

                    b.Navigation("Creature");

                    b.Navigation("Speed");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Encounter", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.Campaign", "Campaign")
                        .WithMany("Encounters")
                        .HasForeignKey("CampaignId")
                        .HasConstraintName("fk_encounters_campaigns_campaign_id");

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.SpellAction", b =>
                {
                    b.HasOne("DND_Initiative_Tracker.Models.ActionEntity", "Action")
                        .WithMany("SpellActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spell_actions_actions_action_id");

                    b.HasOne("DND_Initiative_Tracker.Models.Spell", "Spell")
                        .WithMany("SpellActions")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_spell_actions_spells_spell_id");

                    b.Navigation("Action");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.AbilityScoreType", b =>
                {
                    b.Navigation("CreatureScores");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.ActionEntity", b =>
                {
                    b.Navigation("CreatureActions");

                    b.Navigation("SpellActions");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.AppUser", b =>
                {
                    b.Navigation("CampaignUsers");

                    b.Navigation("OwnedCreatures");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Campaign", b =>
                {
                    b.Navigation("CampaignUsers");

                    b.Navigation("Encounters");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Condition", b =>
                {
                    b.Navigation("CreatureConditions");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Creature", b =>
                {
                    b.Navigation("AbilityScores");

                    b.Navigation("Actions");

                    b.Navigation("Conditions");

                    b.Navigation("CreatureEncounters");

                    b.Navigation("DamageTypes");

                    b.Navigation("Languages");

                    b.Navigation("Senses");

                    b.Navigation("Skills");

                    b.Navigation("Speeds");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.CreatureType", b =>
                {
                    b.Navigation("Creatures");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.DamageType", b =>
                {
                    b.Navigation("CreatureDamageTypes");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Encounter", b =>
                {
                    b.Navigation("CreatureEncounters");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Language", b =>
                {
                    b.Navigation("CreatureLanguages");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Role", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Sense", b =>
                {
                    b.Navigation("CreatureSenses");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Skill", b =>
                {
                    b.Navigation("CreatureSkills");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Speed", b =>
                {
                    b.Navigation("CreatureSpeeds");
                });

            modelBuilder.Entity("DND_Initiative_Tracker.Models.Spell", b =>
                {
                    b.Navigation("SpellActions");
                });
#pragma warning restore 612, 618
        }
    }
}
