  @DND_Initiative_Tracker_HostAddress = http://localhost:8080


  GET {{DND_Initiative_Tracker_HostAddress}}/api/users
  Accept: application/json
  ###
  

  GET {{DND_Initiative_Tracker_HostAddress}}/api/health
  Accept: application/json
  ###
  